# Generated by Django 3.2.25 on 2026-07-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojoudi_label', models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='موجود', max_length=7)),
                ('name', models.CharField(max_length=200)),
                ('inputV', models.PositiveIntegerField()),
                ('outV', models.PositiveIntegerField()),
                ('wattage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('view', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.brand')),
                ('category', models.ManyToManyField(related_name='products', to='product.Category')),
            ],
        ),
    ]
