# Generated by Django 3.2.25 on 2026-07-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_tupe',
            new_name='user_type',
        ),
    ]
