# Generated by Django 3.2.25 on 2026-07-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_tupe_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
