# Generated by Django 3.2.25 on 2026-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'مشتزی'), ('vendor', 'فروشنده')], default='customer', max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
